### ISSUE TITLE
Uncatchable timeout

### ISSUE THREAD

**Issue by xTRiM** [vlio20/utils-decorators#94]
Is it possible to catch the timeout exception somehow? I'm always crashing with "Unhandled promise rejection"

```
UnhandledPromiseRejectionWarning: Error: timeout occurred after 2000
    at new TimeoutError (node_modules/utils-decorators/src/timeout/timeout.ts:6:5)
    at Timeout._onTimeout (node_modules/utils-decorators/src/timeout/timeout.ts:28:20)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by xTRiM** [comment]
My bad, sorry, working as intended.
